spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20180301?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345
  flyway:
    baseline-on-migrate: true
server:
  port: 15015