spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    local环境暂时使用dev数据库
    url: jdbc:mysql://127.0.0.1:3306/openauth?useUnicode=true&characterEncoding=utf8
    username: root
    password: 12345
  application:
    name: auth-server
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  profiles:
    active: local
server:
  port: 15101
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:com/jiuzhou/bootwork/dao/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:15100/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
logging:
  config: classpath:logback-spring.xml
  path: logs/

#  ---------------redis配置------------------------------------------
#jedis:
#  pool:
#    host: 40.73.37.35
#    port: 6379
#    password: ShanshuRedisDev12018$
#    local
jedis:
  pool:
    host: localhost
    port: 6379
    password:
redis:
  preKey: GATEWAY_AUTH_SERVER_