server:
  port: 15022
eureka:
  client:
#  不进行注册的意思
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:15100/eureka/
  instance:
    ip-address: 127.0.0.1:15022
    prefer-ip-address: false
#      defaultZone: http://47.94.134.37:15100/eureka/
#      defaultZone: http://172.17.84.212:15100/eureka/
#      defaultZone: http://127.0.0.1:15011/eureka/,http://127.0.0.1:15012/eureka/
spring:
  application:
      name: fuyou
#      name: eureka-api

logging:
  level: debug
