spring:
  application:
    name: gateway-server
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  profiles:
      active: local
server:
  port: 15102
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://localhost:15100/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: false
logging:
  config: classpath:logback-spring.xml
  path: logs/