eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health