spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hello_test?useUnicode=true
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:com/jiuzhou/bootwork/dao/mapper/*.xml
#  type-aliases-package: com.jiuzhou.bootwork.dao
logging:
  level: debug
server:
  port: 9065
